# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(max_length=255, verbose_name='descrição')),
                ('prefixo', models.CharField(max_length=1, verbose_name='prefixo')),
                ('quantity_of_tickets', models.IntegerField(verbose_name='quanditade')),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=4, verbose_name='senha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('complete_use', models.DateTimeField(null=True, verbose_name='concluída')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Service', verbose_name='serviço')),
            ],
            options={
                'verbose_name': 'senhas',
                'verbose_name_plural': 'senha',
            },
        ),
    ]
