# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=1, verbose_name='Senha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('check_in', models.DateTimeField(auto_now=True, verbose_name='entrada')),
                ('check_out', models.DateTimeField(null=True, verbose_name='saida')),
                ('accesspoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AccessPoint')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(max_length=1, verbose_name='Prefixo')),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(max_length=255, verbose_name='Descrição')),
                ('priority', models.IntegerField()),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(max_length=255, verbose_name='Descrição')),
                ('template', models.CharField(max_length=100, verbose_name='Template')),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Priority'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Service'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
