# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 18:04
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesspoint',
            options={'ordering': ('name',), 'verbose_name': 'Ponto de acesso', 'verbose_name_plural': 'Pontos de acesso'},
        ),
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': 'Contador', 'verbose_name_plural': 'Contadores'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('name',), 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ('name',), 'verbose_name': 'Prioridade', 'verbose_name_plural': 'Prioridades'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('name',), 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(auto_now=True, verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(null=True, verbose_name='Saida'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='ticket',
            field=models.CharField(max_length=4, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='counter',
            name='total',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Total'),
        ),
    ]
