# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(max_length=255, verbose_name='descrição')),
            ],
            options={
                'verbose_name_plural': 'Pontos de acesso',
                'ordering': ('name',),
                'verbose_name': 'Ponto de acesso',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(max_length=255, verbose_name='descrição')),
            ],
            options={
                'verbose_name_plural': 'grupos',
                'ordering': ('name',),
                'verbose_name': 'grupo',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='complete_use',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='concluída'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='emitida em'),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Group', verbose_name='grupo'),
        ),
    ]
