# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161019_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='WorkGroup',
        ),
        migrations.AlterModelOptions(
            name='accesspoint',
            options={'ordering': ('name',), 'verbose_name': 'ponto de acesso', 'verbose_name_plural': 'pontos de acesso'},
        ),
    ]
